export const allJobs = [
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Completed",
    verificationStatus: "Completed",
    paymentStatus: "Paid",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Completed",
    verificationStatus: "Completed",
    paymentStatus: "Paid",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Completed",
    verificationStatus: "Completed",
    paymentStatus: "Paid",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Completed",
    verificationStatus: "Completed",
    paymentStatus: "Paid",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Completed",
    verificationStatus: "Completed",
    paymentStatus: "Paid",
  },
];

export const pendingJobs = [
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Pending",
    hours: "24",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Pending",
    hours: "24",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Pending",
    hours: "24",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Pending",
    hours: "24",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Pending",
    hours: "24",
  },
  {
    id: 210,
    date: "23 - 08 - 2021",
    entity: "NIN",
    type: "ID Verification",
    created: "Paul Kagame",
    status: "Pending",
    hours: "24",
  },
];
